import { Inter } from "next/font/google";
import "./globals.css";
import MyProvider from "../component/Provider";
import ThirdWebProvider from "../component/Provider-thirdWeb";
import RefIdProvider from "../component/RefIdProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SIGMANTARIAN",
  description: "Generated by Bawdicsoft",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ThirdWebProvider>
          <MyProvider>
            <RefIdProvider>{children}</RefIdProvider>
          </MyProvider>
        </ThirdWebProvider> */}
        <div className="flex flex-col items-center justify-center h-screen bg-gray-100 text-center p-6">
          <h1 className="text-4xl md:text-6xl font-bold text-gray-800 mb-4">
            🚧 Website is Under Construction 🚧
          </h1>
          <p className="text-lg md:text-xl text-gray-600">
            We’re working hard to bring you something amazing. Stay tuned!
          </p>
        </div>
      </body>
    </html>
  );
}
