import { Inter } from "next/font/google";
import "./globals.css";
import MyProvider from "../component/Provider";
import ThirdWebProvider from "../component/Provider-thirdWeb";
import RefIdProvider from "../component/RefIdProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SIGMANTARIAN",
  description: "Generated by Bawdicsoft",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThirdWebProvider>
          <MyProvider>
            <RefIdProvider>{children}</RefIdProvider>
          </MyProvider>
        </ThirdWebProvider>
      </body>
    </html>
  );
}
